apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret-dev
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2Nzg5MA==
  COHERE_API_KEY: U09zSjY2M0xNZzQxTjdoZTJ2SW9oWmNkR1E0T1g2RW9KcERtZlpwbw==
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA0SzlCMzhFNlEvQjBBRDYzUkpIQ04vSXBrYUFoTFZRaUtCQVkzSjBWbkt4M1Vs

